server:
  port: 7002

spring:
  application:
    name: jeecg-demo
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: public
        username: nacos
        password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: public
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-dev.yaml
